PREFIX :   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

INSERT DATA {
  :19630126-0001 rdf:type       :SeniorTeacher ;
          :name         "Teacher 1" ;
          :personId         "19630126-0001" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D4-3> .
  
  :19600814-0002 rdf:type       :SeniorTeacher ;
          :name         "Teacher 2" ;
          :personId         "19600814-0002" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-4> .
  
  :19600905-0003 rdf:type       :SeniorTeacher ;
          :name         "Teacher 3" ;
          :personId         "19600905-0003" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-1> .
  
  :19590129-0004 rdf:type       :SeniorTeacher ;
          :name         "Teacher 4" ;
          :personId         "19590129-0004" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D3-3> .
  
  :19610623-0005 rdf:type       :SeniorTeacher ;
          :name         "Teacher 5" ;
          :personId         "19610623-0005" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D5-2> .
  
  :19610620-0006 rdf:type       :SeniorTeacher ;
          :name         "Teacher 6" ;
          :personId         "19610620-0006" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D5-0> .
  
  :19580218-0007 rdf:type       :SeniorTeacher ;
          :name         "Teacher 7" ;
          :personId         "19580218-0007" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D4-1> .
  
  :19570828-0008 rdf:type       :SeniorTeacher ;
          :name         "Teacher 8" ;
          :personId         "19570828-0008" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D4-0> .
  
  :19690408-0009 rdf:type       :SeniorTeacher ;
          :name         "Teacher 9" ;
          :personId         "19690408-0009" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D3-5> .
  
  :19560612-0010 rdf:type       :SeniorTeacher ;
          :name         "Teacher 10" ;
          :personId         "19560612-0010" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D3-2> .
  
  :19570615-0011 rdf:type       :SeniorTeacher ;
          :name         "Teacher 11" ;
          :personId         "19570615-0011" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D5-3> .
  
  :19570826-0012 rdf:type       :SeniorTeacher ;
          :name         "Teacher 12" ;
          :personId         "19570826-0012" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-5> .
  
  :19640414-0013 rdf:type       :SeniorTeacher ;
          :name         "Teacher 13" ;
          :personId         "19640414-0013" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D4-1> .
  
  :19611219-0014 rdf:type       :SeniorTeacher ;
          :name         "Teacher 14" ;
          :personId         "19611219-0014" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-3> .
  
  :19690513-0015 rdf:type       :SeniorTeacher ;
          :name         "Teacher 15" ;
          :personId         "19690513-0015" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-5> .
  
  :19560812-0016 rdf:type       :SeniorTeacher ;
          :name         "Teacher 16" ;
          :personId         "19560812-0016" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D3-1> .
  
  :19580515-0017 rdf:type       :SeniorTeacher ;
          :name         "Teacher 17" ;
          :personId         "19580515-0017" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-3> .
  
  :19601021-0018 rdf:type       :SeniorTeacher ;
          :name         "Teacher 18" ;
          :personId         "19601021-0018" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D1-3> .
  
  :19650303-0019 rdf:type       :SeniorTeacher ;
          :name         "Teacher 19" ;
          :personId         "19650303-0019" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-4> .
  
  :19660630-0020 rdf:type       :SeniorTeacher ;
          :name         "Teacher 20" ;
          :personId         "19660630-0020" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-5> .
  
  :19600529-0021 rdf:type       :SeniorTeacher ;
          :name         "Teacher 21" ;
          :personId         "19600529-0021" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D3-5> .
  
  :19690917-0022 rdf:type       :SeniorTeacher ;
          :name         "Teacher 22" ;
          :personId         "19690917-0022" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D1-3> .
  
  :19620522-0023 rdf:type       :SeniorTeacher ;
          :name         "Teacher 23" ;
          :personId         "19620522-0023" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D2-2> .
  
  :19620831-0024 rdf:type       :SeniorTeacher ;
          :name         "Teacher 24" ;
          :personId         "19620831-0024" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-0> .
  
  :19560705-0025 rdf:type       :SeniorTeacher ;
          :name         "Teacher 25" ;
          :personId         "19560705-0025" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-4> .
  
  :19620424-0026 rdf:type       :SeniorTeacher ;
          :name         "Teacher 26" ;
          :personId         "19620424-0026" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D7-1> .
  
  :19610918-0027 rdf:type       :SeniorTeacher ;
          :name         "Teacher 27" ;
          :personId         "19610918-0027" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D4-3> .
  
  :19680712-0028 rdf:type       :SeniorTeacher ;
          :name         "Teacher 28" ;
          :personId         "19680712-0028" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-0> .
  
  :19640220-0029 rdf:type       :SeniorTeacher ;
          :name         "Teacher 29" ;
          :personId         "19640220-0029" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D6-5> .
  
  :19561222-0030 rdf:type       :SeniorTeacher ;
          :name         "Teacher 30" ;
          :personId         "19561222-0030" ;
          :TeacherInDivision   <http://www.semanticweb.org/user/ontologies/2025/3/untitled-ontology-3/D2-2> .
  
}